
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        pypi_url: https://pypi.org
        pypi_index_url: https://pypi.org/simple
        spec: "main.spec"

    - run: cp -r src/supported_language src/dist/windows/main
    - run: cp -r src/qm src/dist/windows/main
    - run: cp src/custom.txt src/dist/windows/main/custom.txt
    - run: cp src/UnRen-forall.bat src/dist/windows/main/UnRen-forall.bat
    - run: cp src/hook_unrpa.rpy src/dist/windows/main/hook_unrpa.rpy
    - run: cp -r src/custom_engine src/dist/windows/main
    - run: cp src/main.ico src/dist/windows/main/main.ico
    - run: cp src/cacert.pem src/dist/windows/main/cacert.pem

    - uses: actions/upload-artifact@v4
      with:
        name: Action-Build
        path: src/dist/windows/main
