
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src
        pypi_url: https://pypi.org
        pypi_index_url: https://pypi.org/simple
        spec: "main.spec"

    - run: cp src/source.rst src/dist/windows/source.rst
    - run: cp src/target.rst src/dist/windows/target.rst
    - run: cp src/main.ico src/dist/windows/main.ico
    - run: cp src/cacert.pem src/dist/cacert.pem

    - uses: actions/upload-artifact@v4
      with:
        name: Action-Build
        path: src/dist/windows
